version: 2.1

executors:
  build_machine:
    machine:
      image: ubuntu-2204:current
    resource_class: large

commands:
  setup:
    steps:
      - run:
          command: |
            sudo apt-get install -y openjdk-17-jdk
  startings:
    steps:
      - run:
          command: |
            java -jar testfile.jar

jobs:
  st:
    executor: build_machine
    parameters:
      node:
        type: string
        default: "default"
    steps:
      - checkout
      - setup
      - startings

workflows:
  run:
    jobs:
      - st:
          matrix:
            parameters:
              node:
                - "r1"
